# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singlemode.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(800, 290, 111, 61))
        self.confirmButton.setObjectName("confirmButton")
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(800, 630, 111, 61))
        self.exitButton.setObjectName("exitButton")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(620, 630, 111, 61))
        self.backButton.setObjectName("backButton")
        self.manView = QtWidgets.QGraphicsView(self.centralwidget)
        self.manView.setGeometry(QtCore.QRect(20, 180, 551, 521))
        self.manView.setObjectName("manView")
        self.resultBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.resultBrowser.setGeometry(QtCore.QRect(220, 80, 561, 41))
        self.resultBrowser.setObjectName("resultBrowser")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(120, 60, 60, 71))
        self.resultLabel.setObjectName("resultLabel")
        self.letterEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.letterEdit.setGeometry(QtCore.QRect(610, 300, 141, 41))
        self.letterEdit.setObjectName("letterEdit")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(610, 170, 311, 61))
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.judgeLabel = QtWidgets.QLabel(self.centralwidget)
        self.judgeLabel.setGeometry(QtCore.QRect(620, 410, 291, 141))
        self.judgeLabel.setObjectName("judgeLabel")
        self.answerLabel = QtWidgets.QLabel(self.centralwidget)
        self.answerLabel.setGeometry(QtCore.QRect(220, 130, 561, 41))
        self.answerLabel.setText("")
        self.answerLabel.setObjectName("answerLabel")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(310, 10, 341, 61))
        self.titleLabel.setObjectName("titleLabel")
        self.confirmButton.raise_()
        self.exitButton.raise_()
        self.backButton.raise_()
        self.manView.raise_()
        self.resultBrowser.raise_()
        self.resultLabel.raise_()
        self.letterEdit.raise_()
        self.infoLabel.raise_()
        self.answerLabel.raise_()
        self.judgeLabel.raise_()
        self.titleLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 946, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.exitButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.confirmButton.setText(_translate("MainWindow", "确认"))
        self.exitButton.setText(_translate("MainWindow", "退出"))
        self.backButton.setText(_translate("MainWindow", "返回"))
        self.resultBrowser.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\"/></p></body></html>"))
        self.resultBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\"> </span></p></body></html>"))
        self.resultLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">结果</span></p></body></html>"))
        self.judgeLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.titleLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; font-weight:600;\">Hangman 单人模式</span></p></body></html>"))
